//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ComposeOfCheck = new HashSet<ComposeOfCheck>();
        }
    
        public int idProduct { get; set; }
        public string nameProduct { get; set; }
        public Nullable<long> numBarcode { get; set; }
        public Nullable<int> idProducer { get; set; }
        public Nullable<System.DateTime> expirationDate { get; set; }
        public Nullable<int> idPromotion { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComposeOfCheck> ComposeOfCheck { get; set; }
        public virtual Producers Producers { get; set; }
        public virtual Promotions Promotions { get; set; }
    }
}
